import React from "react";
import "../../Styles/Pages/CourseList.css";
import { Link } from "react-router-dom";
import rocketBackground from "../../assets/blade.mp4";

function CourseList() {
  return (
    <div>
      <video
        className="rocketVideo"
        autoPlay
        loop
        muted
        source
        src={rocketBackground}
        type="video/mp4"
      />
      <h1>
        We Scoured the Internet to find you Free and Paid Online Game
        Development Courses
      </h1>
      <div className="course-tables">
        <table>
          <tr>
            <th>Free Online Game Development Courses</th>
            <th>Certificate</th>
          </tr>
          <tr>
            <Link>
              <td>https://www.udemy.com/course/code-your-first-game/</td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.udemy.com/course/introduction-to-game-development-with-unity/
              </td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>https://www.udemy.com/course/unity-game-developer/</td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.udemy.com/course/game-development-crash-course/
              </td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.udemy.com/course/free-prep-for-html5-game-development/
              </td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>https://alison.com/courses/game-development</td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.futurelearn.com/subjects/it-and-computer-science-courses/game-development
              </td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://learn.unity.com/course/beginner-design-unity-game-development-course
              </td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.unrealengine.com/en-US/blog/learn-game-development-for-free-with-unreal-online-learning
              </td>
            </Link>
            <td>x</td>
          </tr>
        </table>
        <table>
          <tr>
            <th>Paid Online Game Development Courses</th>
            <th>Certificate</th>
          </tr>
          <tr>
            <Link>
              <td>https://www.udemy.com/course/code-your-first-game/</td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.udemy.com/course/introduction-to-game-development-with-unity/
              </td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>https://www.udemy.com/course/unity-game-developer/</td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.udemy.com/course/game-development-crash-course/
              </td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.udemy.com/course/free-prep-for-html5-game-development/
              </td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>https://alison.com/courses/game-development</td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>https://www.skillshare.com/browse/game-development</td>
            </Link>
            <td>x</td>
          </tr>
          <tr>
            <Link>
              <td>https://www.coursera.org/courses?query=game%20development</td>
            </Link>
            <td>✔</td>
          </tr>
          <tr>
            <Link>
              <td>
                https://www.futurelearn.com/subjects/it-and-computer-science-courses/game-development
              </td>
            </Link>
            <td>✔</td>
          </tr>
        </table>
      </div>
    </div>
  );
}

export default CourseList;
